#+TITLE: DMG-go

* DMG-go
Hi and welcome to the repo for my (hopefully completed) Gameboy DMG emulator
written in go. This is a first attempt at systems stuff so it's not the best and
quite inaccurate but I hope this can serve as a good learning resource or smth
for other people hoping to attempt the same thing.

* Current features and TODO's
+ [-] Functional (albeit inaccurate) CPU
+ [-] Working PPU (but needs fixing)
+ [-] MBC support [2/4]
  + [X] MBC0
  + [X] MBC1
  + [ ] MBC2
  + [ ] MBC3 (timer not implemented)

* Resources and credits
I used a lot of resources and I also +plagiarized+ +borrowed+
referenced some already existing gameboy/color emulators for
inspiration and to get an idea of how they did their stuff.

[[https://github.com/djhworld/gomeboycolor]] - this is another gameboy-color
emulator written in go that I used as a reference point for a couple of parts of
mine. It's a very well made project and I thank the creator 🙏

[[https://gekkio.fi/files/gb-docs/gbctr.pdf]] - The gameboy technical
reference. This one helped a lot with the creation of the CPU instruction
functions as it helped me clearly see how some of the functions operated

[[https://gbdev.io/gb-opcodes//optables/]] - This is one of quite a few tables that
show all of the CPU instruction functions along with their OPCode and other
stuff, this helped quite a lot with understanding the CPU instructions more as
well as provided me with the json file to easily format and then use these
instructions in my program

[[https://rylev.github.io/DMG-01/public/book/introduction.html]] - I didn't end up
following this one exactly but it was helpful as a baseline to help me
understand the basics of emulating the system and served as a great entry
point. Also really well written (even tho it uses rust 🤢)

[[https://gbdev.io/pandocs]] - The absolute beast, like 90% of the information I
gained came from this, many places tell you to use this and I can see why. It's
amazingly written and while it can be a little bit confusing it's amazing
reference material


[[https://hacktix.github.io/GBEDG/]] - Great for helping with quite a few things
